module "stage" {
  source = "../01_test"

  name = "shyun"
  region = "ap-northeast-3"
  ava = ["a","c"]
  key = "shyun-key"
  cidr_main = "10.0.0.0/16"
  cidr_public = ["10.0.0.0/24","10.0.2.0/24"]
  cidr_private = ["10.0.1.0/24","10.0.3.0/24"]
  cidr_privatedb = ["10.0.4.0/24","10.0.5.0/24"]
  cidr_route = "0.0.0.0/0"
  ipv6_cidr_blocks = "::/0"
  port_http = "80"
  protocol_tcp = "tcp"
  port_ssh = "22"
  port_sql = "3306"
  protocol_http = "HTTP"
  load_type = "application"
  tg_type = "instance"
  ins_type = "t2.micro"
  storage_size = 20
  storage_type = "gp2"
  sql_engine = "mysql"
  dbins_type = "db.t2.micro"
  db_name = "test"
  db_username = "admin"
  db_password = "Bespinbespin1!"
  nul = null
}